; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lonely-gold-serial-controller]

; ================== Platform ==================
platform = espressif32@6.5.0 ; Downgraded to allow proper flash
board = esp32-s3-devkitm-1  ; Not sure why its devkitm
framework = arduino         ; Running on an Arduino Framework
monitor_speed = 115200      ; Monitor Speed 115.2k

; ================== Board Settings (16MB Flash + 8MB OPI PSRAM) ==================
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.partitions = min_spiffs.csv ;Partitions for OTA

build_flags =
    -DCORE_DEBUG_LEVEL=1            ; Proper Debug output

    ; TFT_eSPI config via build flags (bypasses User_Setup.h file lookup)
    -DUSER_SETUP_LOADED=1           ; Tell TFT_eSPI to skip its own User_Setup.h
    -DDISABLE_ALL_LIBRARY_WARNINGS=1
    -DST7735_DRIVER=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DTFT_CS=7
    -DTFT_DC=40
    -DTFT_MOSI=41
    -DTFT_SCLK=42
    -DTFT_RST=39
    -DTFT_MISO=-1
    -DTFT_BL=-1                     ; LED+ hardwired to +3.3V on PCB
    -DSPI_FREQUENCY=10000000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DSMOOTH_FONT=1

; ================== Upload - SERIAL (default) ==================
upload_protocol = esptool
upload_speed = 460800

; ================== Libraries ==================
lib_deps =
    bodmer/TFT_eSPI@2.5.43



; ; OTA env
; [env:lonely-gold-ota]
; extends = env:lonely-gold-serial
; upload_protocol = espota
; upload_port = 10.0.0.57